### ISSUE TITLE
missing file game-debate_jee.csv

### ISSUE THREAD

**Issue by racinmat** [rikurb8/game-debate-scraper#1]
Hi, I need to do some scraping, and I'm reusing your project. But you're reading there file `game-debate_jee.csv` and I can't find where you're creating it. Could you please share it? 
Thanks.

**Comment by rikurb8** [comment]
Hey, it's been a long time since I used this (and the code quality is questionable) but i'm pretty sure the input file is just the output of the main scaper

**Comment by racinmat** [comment]
Oh, I see, thanks, that makes sense.
btw, I ported the scraper to python 3 in my fork and refactored it a bit, should I make a PR?

**Comment by rikurb8** [comment]
No need, this is 100% deprecated for my needs and might remove it anyways. Happy if it helped you
